# This workflow helps to build binero customer documentation

name: Build Binero Customer Docs

on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Tox
        run: sudo apt install tox

      - name: Build docs
        run: tox -e docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html/
