name: Preview build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install tox
        run: sudo apt install -y tox

      - name: Build docs
        run: tox -e docs

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/html/
